### ISSUE TITLE
Cannot create New Preset for check 

### ISSUE THREAD

**Issue by hiteshssaa** [cdrpro-macros/cdr-preflight#1]
While creating new Preset it gives runtime error, While debugging it goes to following line 

![image](https://user-images.githubusercontent.com/59009546/71221135-6b3f6180-22f1-11ea-98b0-a83dfe235d1b.png)

**Comment by hiteshssaa** [comment]
I'm currently Using Corel X8 32 bit on Windows, Any fixes are highly appreciated.

**Comment by SanichKotikov** [comment]
@hiteshssaa I've fixed the issue and updated *.gms file. Could you try and let me know if it works for now?
